debug: false

spring:
  application:
    name: mocko-server
  profiles:
    active: dev
  main:
    banner-mode: Console
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=10240,maximumSize=102400,expireAfterAccess=10m

server:
  port: 8190

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    banner: off

mocko:
  password:
    salt: MayTheForceBeWithYou!