profiles: prod

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./mocko-db
    username: mocko
    password: 8190
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
